config/routes.rb
Rails.application.routes.draw do

root 'articles#top'
resources :articles, :except => [:new, :edit, :update] do
	collection do
		get 'top'
		get 'answer'
	end
	resource :favorites, :only => [:create, :destroy]
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :favorites

	def favorited_by?(session)
		self.favorites.where(session_id: session).exists?
	end
end

app/models/chain_freq.rb
class ChainFreq < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def top
  end

  def answer
		  # ここからpythonスクリプトを実行
	@jiro_copype = `python3 ./main.py`
  	@article = Article.new
  end

  def create
  	article = Article.new(article_path)
  	article.save
	redirect_to articles_path
  end

  def index
  	@articles = Article.page(params[:page]).per(3).reverse_order
  end

  def show
  	@article = Article.find(params[:id])
  end

  def destroy
  	article = Article.find(params[:id])
  	if article.password == params[:password]
  		article.delete
  		redirect_to articles_path
  	else
  		@articles = Article.page(params[:page]).per(3).reverse_order
  		render 'index'
  	end
  end

  private
	def article_path
		params.require(:article).permit(:body, :user_name, :password)
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :get_cookie_to_session, :set_var

	def create
		@favorite = @article.favorites.build(session_id: session[:session_id])
		@favorite.save
	end

	def destroy
		@favorite = Favorite.find_by(article_id: @article.id)
		@favorite.destroy
	end

	private
		def set_var
			@article = Article.find(params[:article_id])
			@articles = Article.page(params[:page]).per(3).reverse_order
		end

		def get_cookie_to_session
			unless cookies[:favo_id].presence
				cookies[:favo_id] = { value: "create_favorite" + current_user.id.to_s, domain: "http://localhost:3000/", expires: 30.days.from_now, path: url_for(only_path: true), secure: false}
				session[:session_id] = cookies[:favo_id]
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/articles/answer.html.erb
<!--コンテンツ全て。 -->
<div class="contents_answer">
	<!-- リザルト画面主要部分。-->
	<div class="page">
		<h2>完飲</h2>
		<!---GIF部分。-->
		<div class="image"></div>
		<!---リザルト画面部分。-->
		<div class="result">
			<form>
				<h2>結果</h2>
				<div><%= simple_format @jiro_copype, class:"copype_text" %></div>
			</form>
		</div>
		<!-- -------------tab----------------- -->
		<div class="tabmenu">
			<!-- tabボタン部分 -->
			<ul class="tab_list">
				<li id="left" class="selected">アーカイブに保存</li>
				<li id="right">SNS共有</li>
			</ul>
			<!-- テクスト？ -->
			<div class="tab">
				<div class="left">
					
					<%= form_for @article, :html => { :class => "form-group form-field"} do |f|%>
						<%= f.hidden_field :body, :value =>@jiro_copype %>
						<label for="exampleInputEmail1">ニックネーム</label>
						<%= f.text_field :user_name, class: "form-control"%><br>
						<p class="form-text text-muted">削除用パスワードを入力してください</p>
						<%= f.password_field :password, class: "form-control" %>
						<%= f.submit "投稿",class: "btn btn-dark pull-right submit_btn" %>
					<% end -%>


				</div>

				<div class="right">
					<%= link_to "http://twitter.com/home?status=#{url_for(only_path: false)}" do %>
						<%= fa_icon "twitter", class: "fab fa-twitter-square fa-w-14 fa-5x"%>
						<span class="blinking">
							⬅︎ クリックでTwitterに共有せよ
						</span>

					<% end -%>
				</div>
			</div>
		</div>
		<!-- -----------------tab fin------------------ -->
		<!---テクスト部分。-->
		<div class="text">
			<p class="success">
				完飲成功....
			</p>
		</div>
		<!---ボタン部分。-->
		<div class="button">
			<ul class="menu answer_menu clearfix">
				<li class="archive"><%= link_to "アーカイブ", articles_path %></li>
				<li class="regenerator"><%= link_to "もう一度", answer_articles_path %> </li>
			</ul>
		</div>
		<!---いいね部分。-->
		<%= link_to root_path do %><div class="share"></div><% end %>
	</div>
</div>

app/views/articles/index.html.erb
<!--コンテンツ全て。 -->
<div class="contents_archive">
	<!-- アーカイブ主要部分。-->
	<div class="page">
		<!-- 上部テクスト部分。-->
		<div class="head_text">
			<h2>兵たちが夢のあと...</h2><br>
			<hr>
			<p>ジロリアン達による歴戦の架空コピペ投稿が見れます。</p>
		</div>
		<!-- ポスト大枠部分。-->
		<div class="timeline">
			<!-- 個別ポスト部分。-->
			<% @articles.each do |article| %>
			<div class="post">
				<p class="index_p">作成日時: </p><%=link_to article.created_at.strftime('%Y.%m.%d'), article_path(article.id) %><br>
				<p class="index_p">架空の本文: </p><%= simple_format(article.body) %><br>
				<p class="index_p">ニックネーム: </p><%= article.user_name %><br>
				<!---いいね部分。-->
				<%= render partial: "favorites/favorite", locals: { article: article } %>

				<!-- モーダル -->
				<a data-target="<%= article.id %>" class="modal-open">削除</a>

				<div id="<%= article.id %>" class="modal-content">

					<p>削除用のパスワードを入力してください</p>
					<%= form_tag(article, :url => {:controller => :articles, :action => :destroy}, :method => :delete) do %>
					<%= text_field_tag :password %>
					<%= hidden_field_tag :id, value: article.id %>
					<%= submit_tag "削除" %>
					<% end %>
					<p><a class="modal-close">閉じる</a></p>

				</div>

			</div>
			<% end %>
			<%= paginate @articles %>
		</div>

		<!-- ボタン部分。-->
		<div class="button">
			<ul class="menu clearfix">
				<li>
					<%= link_to "TOPへ戻る", root_path, class: "regenerator_2" %>
				</li>
			</ul>
		</div>	
	</div>
</div>

app/views/articles/show.html.erb
 <!--コンテンツ全て。 -->
 <div class="contents_detail">
 	<!-- アーカイブ主要部分。-->
 	<div class="page">
 		<!-- 上部テクスト部分。-->
 		<div class="head_text">
 			<h2>詳細</h2><br>
 			<hr>
 		</div>
 		<!-- ポスト大枠部分。-->
 		<div class="timeline_detail">
 			<!-- 個別ポスト部分。-->
 			<div class="post_detail">
			 	<%= @article.created_at.strftime('%Y.%m.%d')%>
 				<%= label :body, @jiro_copype %>：
 				<br>
 				<%= simple_format(@article.body) %>
 				<br>
 				<span>ユーザー名: </span><%= @article.user_name %><br>
				<span>完飲数: </span><span><%= @article.favorites.count %>杯</spanp>
 			</div>
 		</div>
 		<!-- ボタン部分。-->
 		<div class="button">
 			<ul class="menu clearfix">
 				<li>
				 	<%= link_to "TOPへ戻る", root_path, class: "regenerator_2" %>
 				</li>
 			</ul>
 		</div>	
 	</div>
 </div>

app/views/articles/top.html.erb
		<div class="contents">
		 <!-- ジェネレーター主要部分。-->
			<div class="page">
				<!---GIF部分。-->
				<div class="image">
				</div>
				<!---テクスト部分。-->
				<div class="text">
				    <hr>
					<p>
						二郎の架空コピペが自動生成できます。<br>
						<strong>ジェネレート</strong>ボタンを押して、その目で確かめてください
					</p>
			    </div>
			    <!---白塗りテクスト部分。-->
				<div class="blank">
					<p>全ての二郎を愛する兵たちへ...</p>
				</div>
				<!---ボタン部分。-->
		        <div class="button">
					<ul class="menu clearfix">
						<li class="generator"><%= link_to "ジェネレート", answer_articles_path %></li>
						<li class="archive"><%=link_to "アーカイブ", articles_path %></li>
					</ul>
			    </div>
			</div>
		</div>

app/views/favorites/_favorite.html.erb
<% if article.favorited_by?(session[:session_id]) %>
	<%# binding.pry %>
	<%= link_to article_favorites_path(article_id: article.id), remote: true, method: :delete do %>
		<div class="favo_img share_archive" id="favorite-btn-<%= article.id %>"></div>
	<% end %>
<% else %>
	<%= link_to article_favorites_path(article_id: article.id), remote: true, method: :post do %>
		<div class="favo_img share_archive_fav" id="favorite-btn-<%= article.id %>"></div>
	<% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite-btn-<%= @article.id %>").html("<%= j(render partial: 'favorite', locals: { article: @article}) %>")

app/views/favorites/destroy.js.erb
$("#favorite-btn-<%= @article.id %>").html("<%= j(render partial: 'favorite', locals: { article: @article}) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JirokkasonRails</title>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag() %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <meta name="viewport" content="width=device-width",user-scalable=yes/>
</head>
  <body>
    <!-- /header -->
    <header>
      <%= link_to root_path do %><h1 class="wow wobble" style="font-size: 40px;">ジェネ二郎</h1><% end %>
      <hr>
    </header>
    <%= yield %>
    <footer>
      <div class="banner"></div>
    </footer>
    <script>
      new WOW().init();
    </script>
  </body>
</html>